
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Absent extends javax.swing.JFrame {

    /**
     * Creates new form Absent
     */
    public Absent() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        
       setIcon();
       
       // this.setResizable(false);
    }
     public void setIcon()
    {
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sc_logo.png")));
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gc.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_last_name = new javax.swing.JTextField();
        txt_first_name = new javax.swing.JTextField();
        txt_student_id = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_middle_name = new javax.swing.JTextField();
        txt_mob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        print_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttx_print = new javax.swing.JTextArea();
        send_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Refresh_btn = new javax.swing.JButton();
        report_date = new javax.swing.JTextField();
        txt_stand = new javax.swing.JTextField();
        Issu_date = new javax.swing.JTextField();
        Res = new javax.swing.JComboBox<>();
        Refresh_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notice Print(Write here to send notice via sms)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 101, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("Current Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 120, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Absent Report");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Standard");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setText("Reason");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 70, 30));

        txt_last_name.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(txt_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 280, 37));

        txt_first_name.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(txt_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 280, 37));

        txt_student_id.setFont(new java.awt.Font("Book Antiqua", 0, 16)); // NOI18N
        jPanel1.add(txt_student_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 170, 30));

        txt_address.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 380, 37));

        txt_middle_name.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(txt_middle_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 280, 37));

        txt_mob.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        txt_mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mobKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mobKeyTyped(evt);
            }
        });
        jPanel1.add(txt_mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 200, 37));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setText("Address");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 70, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setText("Middle Name");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 30));

        print_btn.setBackground(new java.awt.Color(22, 101, 158));
        print_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        print_btn.setForeground(new java.awt.Color(255, 255, 255));
        print_btn.setText("Print");
        print_btn.setToolTipText("Print");
        print_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        jPanel1.add(print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 110, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("Last Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        ttx_print.setColumns(20);
        ttx_print.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        ttx_print.setRows(5);
        jScrollPane1.setViewportView(ttx_print);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 690, 620));

        send_btn.setBackground(new java.awt.Color(22, 101, 158));
        send_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        send_btn.setForeground(new java.awt.Color(255, 255, 255));
        send_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail-message-send-icon.png"))); // NOI18N
        send_btn.setText("Send");
        send_btn.setToolTipText("SMS");
        send_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });
        jPanel1.add(send_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 140, 30));

        save_btn.setBackground(new java.awt.Color(22, 101, 158));
        save_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("Save");
        save_btn.setToolTipText("Save");
        save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 110, 30));

        Back_btn.setBackground(new java.awt.Color(22, 101, 158));
        Back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow-Back-3-icon.png"))); // NOI18N
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 30, 40, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("Mob");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 50, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Issue Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 90, 30));

        Refresh_btn.setBackground(new java.awt.Color(22, 101, 158));
        Refresh_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        Refresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        Refresh_btn.setText("Clear");
        Refresh_btn.setToolTipText("Clear");
        Refresh_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 110, 30));

        report_date.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(report_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 200, 37));

        txt_stand.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(txt_stand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, 37));

        Issu_date.setFont(new java.awt.Font("Kruti Dev 051", 0, 25)); // NOI18N
        jPanel1.add(Issu_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 200, 37));

        Res.setFont(new java.awt.Font("Kruti Dev 021", 0, 25)); // NOI18N
        Res.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xSjgtj", "xSj&orZu" }));
        jPanel1.add(Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 190, 37));

        Refresh_btn1.setBackground(new java.awt.Color(22, 101, 158));
        Refresh_btn1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        Refresh_btn1.setForeground(new java.awt.Color(255, 255, 255));
        Refresh_btn1.setText("Delete All");
        Refresh_btn1.setToolTipText("Delete");
        Refresh_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobKeyPressed

    private void txt_mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobKeyTyped
        // TODO add your handling code here:

        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_mobKeyTyped

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        try {
            // TODO add your handling code here:
            ttx_print.print();
            
        } catch (PrinterException ex) {
            Logger.getLogger(Absent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
        
        String a=Res.getSelectedItem().toString();
        String b=Issu_date.getText();
        if(a.equals("xSjgtj"))
        {
            try {
			// Construct data
			String apiKey = "apikey=" + "3GOVz3IiClk-mvKVagPUKvEBSzp0eCfRKI6qjL8ECZ";//GURU
			String message = "&message="+"आपला पाल्य "+"दिनांक "+b+" रोजी गैरहजर होता,याची पालकांनी नोंद घ्यावी,(Gurukul Coaching Classes).";
			String sender = "&sender=" +"GURUKL";
                        String numb=txt_mob.getText();
			String numbers = "&numbers=" +numb;
			String unicode="&unicode="+"true";
			// Send data
			HttpURLConnection conni = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender + unicode;
			conni.setDoOutput(true);
			conni.setRequestMethod("POST");
			conni.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conni.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conni.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
                       
			while ((line = rd.readLine()) != null) {
                            
                            //JOptionPane.showMessageDialog(null, "Message\n"+line);
                            
				stringBuffer.append(line);
                                //System.out.println("the value of line is\t"+line);
                                if(line.startsWith("{\"errors\""))
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Sorry Error Occured");
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Message Send Successfully");
                                }
                                    
			}
			rd.close();
			
			//return stringBuffer.toString();
		} 
                                catch (HeadlessException | IOException ex) {
			/*System.out.println("Error SMS "+e);
			return "Error "+e;*/
                        JOptionPane.showMessageDialog(null,ex+ "\n\nMessage Send Not Successfully");
		}
            
        }
        else if(a.equals("xSj&orZu"))
        {
            try {
			// Construct data
			String apiKey = "apikey=" + "3GOVz3IiClk-mvKVagPUKvEBSzp0eCfRKI6qjL8ECZ";//GURU
			String message = "&message=" +"आपला पाल्याने "+"दिनांक "+b+" रोजी गैरवर्तन केले आहे,याची पालकांनी नोंद घ्यावी,(Guruul Coaching Classes).";
			String sender = "&sender=" +"GURUKL";
                        String numb=txt_mob.getText();
			String numbers = "&numbers=" +numb;
                        String unicode="&unicode="+"true";
			
			// Send data
			HttpURLConnection conni = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender + unicode;
			conni.setDoOutput(true);
			conni.setRequestMethod("POST");
			conni.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conni.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conni.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
                       
			while ((line = rd.readLine()) != null) {
                            
                            //JOptionPane.showMessageDialog(null, "Message\n"+line);
                            
				stringBuffer.append(line);
                                //System.out.println("the value of line is\t"+line);
                                if(line.startsWith("{\"errors\""))
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Sorry Error Occured");
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Message Send Successfully");
                                }
                                    
			}
			rd.close();
			
			//return stringBuffer.toString();
		} 
                                catch (HeadlessException | IOException ex) {
			/*System.out.println("Error SMS "+e);
			return "Error "+e;*/
                        JOptionPane.showMessageDialog(null,ex+ "\n\nMessage Send Not Successfully");
		}
         
        }
        
      
    }//GEN-LAST:event_send_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        String ch=Res.getSelectedItem().toString();
        String a=txt_last_name.getText();
        String b=txt_first_name.getText();
        String c=txt_middle_name.getText();
        String d=txt_stand.getText();
        String e=Issu_date.getText();
        String f=report_date.getText();
        String g=txt_mob.getText();
        String h=txt_address.getText();
        String aa=txt_student_id.getText();
       
        if(!aa.isEmpty())
        {
            
        
      
        try
        {
            
            String sql="insert into Absent values(?,?,?,?,?,?,?,?,?,?)";
                        pst=conn.prepareStatement(sql);
                        pst.setString(1,txt_student_id.getText());
                        pst.setString(2, txt_first_name.getText());
                        pst.setString(3, txt_last_name.getText());
                        pst.setString(4, txt_middle_name.getText());
                        pst.setString(5, txt_mob.getText());
                        pst.setString(6, txt_address.getText());
                        pst.setString(7, Issu_date.getText());
                        pst.setString(8, report_date.getText());
                        pst.setString(9, txt_stand.getText());
                        pst.setString(10, ch);
                        /*
                                \t\tlkro dksafpaax Dyklsl-\n" +
                                        "\t      nRr pSrU; uxj ikpksjk jksM tkeusj- \n
                                */
                        int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
                        if(p==0)
                        {
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "Saved");
                            if(ch.equals("xSjgtj"))                                
                              
                            {
                                ttx_print.append("\t\txq#dwy dksfpax Dyklsl\n\t      okdh jksM]uodkj IYkk>k dWkIYksDl \n\t\trk tkeusj ftYgk tGxko-\n \t\tfnaukad  " + f + "\n\n\t\t     rdzkj-\nfo|kkfFkZ uko&  " + a + " " + b + " " + c + " \nb;Rrk&  " + d + "\niRrk&  " + h + "\n  fo\"k;&vkiyk ikY; xSjgtj jkg.;kckcr-\nekufu; " + c + " " + a + " vki.kkl dGfo.;kr ;srs fd + fnukad \n " + e + "\njksth vkiyk ikY; xSjgtj gksrk-\nrqeP;k ikY;kPkh xSjgtjh dGkoh Eg.kqu rqEgkyk\nuksVhl ikBoyh tkr vkgs-\n\n \nikydkaPkh Lok{kjh\t\t\t lj@ eWMe\n\t\t\t\t   Lok{kjh");
                            } else if(ch.equals("xSj&orZu")) {
                                
                                ttx_print.append("\t\txq#dwy dksfpax Dyklsl\n\t      okdh jksM]uodkj IYkk>k dWkIYksDl \n\t\trk tkeusj ftYgk tGxko-\n \t\tfnaukad  " + f + "\n\n\t\t     rdzkj-\nfo|kkfFkZ uko&  " + a + " " + b + " " + c + " \nb;Rrk&  " + d + "\niRrk&  " + h + "\n  fo\"k;&vkiY;k ikY;kP;k xSj&orZuk ckcr\nekufu; " + c + " " + a + " vki.kkl dGfo.;kr ;srs fd + \nfnukad  " + e + "\njksth vkiY;k ikY;kus DYkkle/;s xSj&orZu dsys vkgs-\nikydkauk lwfpr dj.;kr ;srs fd- R;kauh vkiY;k ikY;kP;k\nlq/kkj.ksdMs y{k |kos- o vkiY;k ikY;kP;k fu;fer\ncWPkyk vkePkk'kh \nlaokn lk/kkok ---**lkro lj@eWMe**---  \n\n ikydkaPkh Lok{kjh\t\t\tlkro lj@ eWMe\n\t\t\t\t   Lok{kjh");
                            }

                        }  
            
        }
        catch(HeadlessException | SQLException ex)
        {
           JOptionPane.showMessageDialog(null,"Sorry Error Occure\n"+ex);
 
        }
         finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry Error Occure\n");
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
        
        new HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_btnActionPerformed

    private void Refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_btnActionPerformed
        // TODO add your handling code here:
        txt_student_id.setText("");
        txt_last_name.setText("");
        txt_first_name.setText("");
        txt_middle_name.setText("");
        txt_stand.setText("");
        Res.setSelectedIndex(0);
        Issu_date.setText("");
        report_date.setText("");
        txt_mob.setText("");
        txt_address.setText("");
        ttx_print.setText("");
    }//GEN-LAST:event_Refresh_btnActionPerformed

    private void Refresh_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_btn1ActionPerformed
        // TODO add your handling code here:
         Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        try
        {
         String sql="delete from Absent";
                pst=conn.prepareStatement(sql);
                int p=JOptionPane.showConfirmDialog(null,"Do you want to Delete","Conform Delete",JOptionPane.YES_NO_OPTION);
                if(p==0)
                {
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Deleted");
                }
        }
       catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Sorry Error Occured\n"+ex);
            
        }
         finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_Refresh_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JTextField Issu_date;
    private javax.swing.JButton Refresh_btn;
    private javax.swing.JButton Refresh_btn1;
    private javax.swing.JComboBox<String> Res;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextField report_date;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton send_btn;
    private javax.swing.JTextArea ttx_print;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_middle_name;
    private javax.swing.JTextField txt_mob;
    private javax.swing.JTextField txt_stand;
    private javax.swing.JTextField txt_student_id;
    // End of variables declaration//GEN-END:variables
}
