
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Class_fees_3 extends javax.swing.JFrame {

    /**
     * Creates new form Class_fees_3
     */
    public Class_fees_3() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        update_table();
        setIcon();
    }
    public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gc.png")));
    }
     public void update_table()
    {
        Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    conn=JavaConnect.ConnectDB();
        try
        {
            /*
            update table
            */
         String sql="select Student_id,First_Name,Last_Name,F_date,F_fill_fees,F_remain,S_date,S_fill_fees,S_remain,T_date,T_fill_fees,T_remain,Ft_date,Ft_fill_fees,Ft_remain from Class_fees_3 order by Student_id";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            class_3_table.setModel(DbUtils.resultSetToTableModel(rs));
           // rs=pst.executeQuery();

        }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(null,"Exception 8 "+e);
         }
        finally
        {
            try
            {
              if(rs!=null)
              {
                  rs.close();
                  
              }
              if(pst!=null)
              {
                  pst.close();
              }
              if(conn!=null)
              {
                  conn.close();
              }
            }
            catch(SQLException ex)
            {
               JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        class_3_table = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        remain_txt_1 = new javax.swing.JTextField();
        fill_fees_1 = new javax.swing.JTextField();
        date_txt_1 = new com.toedter.calendar.JDateChooser();
        Receipt_btn_1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        remain_txt_2 = new javax.swing.JTextField();
        fill_fees_2 = new javax.swing.JTextField();
        date_txt_2 = new com.toedter.calendar.JDateChooser();
        Receipt_btn_2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        remain_txt_3 = new javax.swing.JTextField();
        fill_fees_3 = new javax.swing.JTextField();
        date_txt_3 = new com.toedter.calendar.JDateChooser();
        Receipt_btn_3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        remain_txt_4 = new javax.swing.JTextField();
        fill_fees_4 = new javax.swing.JTextField();
        date_txt_4 = new com.toedter.calendar.JDateChooser();
        Receipt_btn_4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Class_3_area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_last_name = new javax.swing.JTextField();
        txt_first_name = new javax.swing.JTextField();
        txt_middle_name = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_student_id = new javax.swing.JTextField();
        Search_btn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        new_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        print_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Class 3rd,Fees Sturcture");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 108, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        class_3_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(class_3_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 490, 1360, 220));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(22, 108, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel31.setText("Fill Fees");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel32.setText("Date");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel33.setText("Remain Fees");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(" 1st Period");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        remain_txt_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remain_txt_1KeyTyped(evt);
            }
        });
        jPanel1.add(remain_txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));

        fill_fees_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fill_fees_1KeyTyped(evt);
            }
        });
        jPanel1.add(fill_fees_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));
        jPanel1.add(date_txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        Receipt_btn_1.setBackground(new java.awt.Color(22, 101, 158));
        Receipt_btn_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Receipt_btn_1.setForeground(new java.awt.Color(255, 255, 255));
        Receipt_btn_1.setText("Receipt");
        Receipt_btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receipt_btn_1ActionPerformed(evt);
            }
        });
        jPanel1.add(Receipt_btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jTabbedPane1.addTab("First Period", jPanel1);

        jPanel3.setBackground(new java.awt.Color(22, 108, 158));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" 2nd Period");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel34.setText("Fill Fees");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel36.setText("Date");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 30));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel37.setText("Remain Fees");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        remain_txt_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remain_txt_2KeyTyped(evt);
            }
        });
        jPanel3.add(remain_txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));

        fill_fees_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fill_fees_2KeyTyped(evt);
            }
        });
        jPanel3.add(fill_fees_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));
        jPanel3.add(date_txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        Receipt_btn_2.setBackground(new java.awt.Color(22, 101, 158));
        Receipt_btn_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Receipt_btn_2.setForeground(new java.awt.Color(255, 255, 255));
        Receipt_btn_2.setText("Receipt");
        Receipt_btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receipt_btn_2ActionPerformed(evt);
            }
        });
        jPanel3.add(Receipt_btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jTabbedPane1.addTab("Second Period", jPanel3);

        jPanel4.setBackground(new java.awt.Color(22, 108, 158));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel38.setText("Fill Fees");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel39.setText("Date");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 30));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel40.setText("Remain Fees");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText(" 3rd Period");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        remain_txt_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remain_txt_3KeyTyped(evt);
            }
        });
        jPanel4.add(remain_txt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));

        fill_fees_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fill_fees_3KeyTyped(evt);
            }
        });
        jPanel4.add(fill_fees_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));
        jPanel4.add(date_txt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        Receipt_btn_3.setBackground(new java.awt.Color(22, 101, 158));
        Receipt_btn_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Receipt_btn_3.setForeground(new java.awt.Color(255, 255, 255));
        Receipt_btn_3.setText("Receipt");
        Receipt_btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receipt_btn_3ActionPerformed(evt);
            }
        });
        jPanel4.add(Receipt_btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jTabbedPane1.addTab("Third Period", jPanel4);

        jPanel5.setBackground(new java.awt.Color(22, 108, 158));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel41.setText("Fill Fees");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 70, 30));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel42.setText("Date");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 30));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel43.setText("Remain Fees");
        jPanel5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText(" 4th Period");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        remain_txt_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remain_txt_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remain_txt_4KeyTyped(evt);
            }
        });
        jPanel5.add(remain_txt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));

        fill_fees_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fill_fees_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fill_fees_4KeyTyped(evt);
            }
        });
        jPanel5.add(fill_fees_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));

        date_txt_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(date_txt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        Receipt_btn_4.setBackground(new java.awt.Color(22, 101, 158));
        Receipt_btn_4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Receipt_btn_4.setForeground(new java.awt.Color(255, 255, 255));
        Receipt_btn_4.setText("Receipt");
        Receipt_btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receipt_btn_4ActionPerformed(evt);
            }
        });
        jPanel5.add(Receipt_btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jTabbedPane1.addTab("Fourth Period", jPanel5);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 630, 330));

        Class_3_area.setEditable(false);
        Class_3_area.setColumns(20);
        Class_3_area.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        Class_3_area.setRows(5);
        jScrollPane2.setViewportView(Class_3_area);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 680, 330));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, 30));

        txt_last_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 30));

        txt_first_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 200, 30));

        txt_middle_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_middle_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 200, 30));

        delete_btn.setBackground(new java.awt.Color(22, 101, 158));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel2.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 100, 30));

        update_btn.setBackground(new java.awt.Color(22, 101, 158));
        update_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel2.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 110, 30));

        txt_student_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txt_student_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, 170, 30));

        Search_btn.setBackground(new java.awt.Color(22, 102, 158));
        Search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search-icon.png"))); // NOI18N
        Search_btn.setToolTipText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 40, 30, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setText("Middle Name");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 120, 30));

        new_btn.setBackground(new java.awt.Color(22, 101, 158));
        new_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_btn.setForeground(new java.awt.Color(255, 255, 255));
        new_btn.setText("New");
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });
        jPanel2.add(new_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 80, 30));

        Back_btn.setBackground(new java.awt.Color(22, 101, 158));
        Back_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow-Back-3-icon.png"))); // NOI18N
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        print_btn1.setBackground(new java.awt.Color(22, 101, 158));
        print_btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print_btn1.setForeground(new java.awt.Color(255, 255, 255));
        print_btn1.setText("Print");
        print_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(print_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();

        try
        {

          

                String sql="select * from Class_fees_3 where Student_id=?";
                String st=txt_student_id.getText();
                if(st.isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Search Field is Empty");
                }
                else
                {
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,txt_student_id.getText());
                    rs=pst.executeQuery();
                    if(rs.next())
                    {

                         String b=rs.getString("Last_Name");
                        txt_last_name.setText(b);
                        String c=rs.getString("First_Name");//
                        txt_first_name.setText(c);
                        String d=rs.getString("Middle_Name");
                        txt_middle_name.setText(d);
                        String e=rs.getString("F_date");
                        ((JTextField)date_txt_1.getDateEditor().getUiComponent()).setText(e);
                        String f=rs.getString("F_fill_fees");
                        fill_fees_1.setText(f);
                        String g=rs.getString("F_remain");
                        remain_txt_1.setText(g);
                        String h=rs.getString("S_date");
                       ((JTextField)date_txt_2.getDateEditor().getUiComponent()).setText(h);
                        String i=rs.getString("S_fill_fees");
                        fill_fees_2.setText(i);
                        String j=rs.getString("S_remain");
                        remain_txt_2.setText(j);
                        String k=rs.getString("T_date");
                        ((JTextField)date_txt_3.getDateEditor().getUiComponent()).setText(k);
                        String l=rs.getString("T_fill_fees");
                        fill_fees_3.setText(l);
                        String m=rs.getString("T_remain");
                        remain_txt_3.setText(m);
                        String n=rs.getString("Ft_date");
                        ((JTextField)date_txt_4.getDateEditor().getUiComponent()).setText(n);
                        String o=rs.getString("Ft_fill_fees");
                        fill_fees_4.setText(o);
                        String p=rs.getString("Ft_remain");
                        remain_txt_4.setText(p);
                        

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Sorry Not Found");
                    }

                }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Sorry Error Occured\n"+ex);
            
        }
         finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
    }//GEN-LAST:event_Search_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        // TODO add your handling code here:
        txt_student_id.setText("");
        txt_first_name.setText("");
        txt_middle_name.setText("");
        txt_last_name.setText("");
        fill_fees_1.setText("");
        remain_txt_1.setText("");
        fill_fees_2.setText("");
        remain_txt_2.setText("");
        fill_fees_3.setText("");
        remain_txt_3.setText("");
        fill_fees_4.setText("");
        remain_txt_4.setText("");
        ((JTextField)date_txt_4.getDateEditor().getUiComponent()).setText("");
         ((JTextField)date_txt_3.getDateEditor().getUiComponent()).setText("");
          ((JTextField)date_txt_2.getDateEditor().getUiComponent()).setText("");
           ((JTextField)date_txt_1.getDateEditor().getUiComponent()).setText("");
           Class_3_area.setText("");
            update_table();
    }//GEN-LAST:event_new_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
         Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
       
        String aa=txt_student_id.getText();
        String a=txt_first_name.getText();
        String b=txt_middle_name.getText();
        String c=txt_last_name.getText();
        
        String d=((JTextField)date_txt_1.getDateEditor().getUiComponent()).getText();
        String e=fill_fees_1.getText();
        String f=remain_txt_1.getText();
        String g=((JTextField)date_txt_2.getDateEditor().getUiComponent()).getText();
        String h=fill_fees_2.getText();
        String i=remain_txt_2.getText();
        String j=((JTextField)date_txt_3.getDateEditor().getUiComponent()).getText();
        String k=fill_fees_3.getText();
        String l=remain_txt_3.getText();
        String m=((JTextField)date_txt_4.getDateEditor().getUiComponent()).getText();
        String n=fill_fees_4.getText();
        String o=remain_txt_4.getText();
        try
        {
            if(txt_student_id.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter Student Id");
                
                
            }
            else
            {
                 String sql="update Class_fees_3 set First_Name='"+a+"',Middle_name='"+b+"',Last_Name='"+c+"',F_date='"+d+"',F_fill_fees='"+e+"',F_remain='"+f+"',S_date='"+g+"',S_fill_fees='"+h+"',S_remain='"+i+"',T_date='"+j+"',T_fill_fees='"+k+"',T_remain='"+l+"',Ft_date='"+m+"',Ft_fill_fees='"+n+"',Ft_remain='"+o+"' where Student_id='"+aa+"'";
                        pst=conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"UPDATED Successfully");
                
            }
            
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"Sorry Error Occured\n"+ex);
            
        }
         finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        try
        {
            if(txt_student_id.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please Enter Student Id");
            }
            else
            {
                String ab=txt_student_id.getText();
                String sql="delete from Class_fees_3 where Student_id='"+ab+"'";
                pst=conn.prepareStatement(sql);
                int p=JOptionPane.showConfirmDialog(null,"Do you want to Delete","Conform Delete",JOptionPane.YES_NO_OPTION);
                if(p==0)
                {
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Deleted");
                }
            }
            
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Sorry Error Occured\n"+ex);
            
        }
         finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void Receipt_btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receipt_btn_1ActionPerformed
        // TODO add your handling code here:
         String a=((JTextField)date_txt_1.getDateEditor().getUiComponent()).getText();
        String b=fill_fees_1.getText();
        String c=remain_txt_1.getText();
        String d=txt_last_name.getText();
        String e=txt_first_name.getText();
        String f=txt_middle_name.getText();
        Class_3_area.append("\t   ****Gurukul Coaching Classes****"
                + "\n  Tal-jamner,Dist-Jalgoan,Mob:+919922620088"
                + "\n--------------------------------------------------------"
                +"\nStudent Name: "+d+" "+e+" "+f
                + "\n 1st Period"
                + "\n ------------\n"
                + "\n\t       Date:   "+a+""
                + "\n\t  Fill Fees:   "+b+""
                + "\n\tRemain Fees:   "+c+"\n\t-----------------------------------------------");
    }//GEN-LAST:event_Receipt_btn_1ActionPerformed

    private void Receipt_btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receipt_btn_2ActionPerformed
        // TODO add your handling code here:
         String a=((JTextField)date_txt_2.getDateEditor().getUiComponent()).getText();
        String b=fill_fees_2.getText();
        String c=remain_txt_2.getText();
         String d=txt_last_name.getText();
        String e=txt_first_name.getText();
        String f=txt_middle_name.getText();
        Class_3_area.append("\t   ****Gurukul Coaching Classes****"
                + "\n  Tal-jamner,Dist-Jalgoan,Mob:+919922620088"
                + "\n--------------------------------------------------------"
                 +"\nStudent Name: "+d+" "+e+" "+f
                + "\n 2st Period"
                + "\n ------------\n"
                + "\n\t       Date:   "+a+""
                + "\n\t  Fill Fees:   "+b+""
                + "\n\tRemain Fees:   "+c+"\n\t-----------------------------------------------");
    }//GEN-LAST:event_Receipt_btn_2ActionPerformed

    private void Receipt_btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receipt_btn_3ActionPerformed
        // TODO add your handling code here:
         String a=((JTextField)date_txt_3.getDateEditor().getUiComponent()).getText();
        String b=fill_fees_3.getText();
        String c=remain_txt_3.getText();
         String d=txt_last_name.getText();
        String e=txt_first_name.getText();
        String f=txt_middle_name.getText();
        Class_3_area.append("\t   ****Gurukul Coaching Classes****"
                + "\n  Tal-jamner,Dist-Jalgoan,Mob:+919922620088"
                + "\n--------------------------------------------------------"
                 +"\nStudent Name: "+d+" "+e+" "+f
                + "\n 3st Period"
                + "\n ------------\n"
                + "\n\t       Date:   "+a+""
                + "\n\t  Fill Fees:   "+b+""
                + "\n\tRemain Fees:   "+c+"\n\t-----------------------------------------------");
    }//GEN-LAST:event_Receipt_btn_3ActionPerformed

    private void Receipt_btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receipt_btn_4ActionPerformed
        // TODO add your handling code here:
         String a=((JTextField)date_txt_4.getDateEditor().getUiComponent()).getText();
        String b=fill_fees_4.getText();
        String c=remain_txt_4.getText();
         String d=txt_last_name.getText();
        String e=txt_first_name.getText();
        String f=txt_middle_name.getText();
        Class_3_area.append("\t   ****Gurukul Coaching Classes****"
                + "\n  Tal-jamner,Dist-Jalgoan,Mob:+919922620088"
                + "\n--------------------------------------------------------"
                +"\nStudent Name: "+d+" "+e+" "+f
                + "\n 4st Period"
                + "\n ------------\n"
                + "\n\t       Date:   "+a+""
                + "\n\t  Fill Fees:   "+b+""
                + "\n\tRemain Fees:   "+c+"\n\t-----------------------------------------------");
    }//GEN-LAST:event_Receipt_btn_4ActionPerformed

    private void print_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btn1ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            Class_3_area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Class_fees_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_btn1ActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
       
        new HomePage().setVisible(true);
         dispose();
    }//GEN-LAST:event_Back_btnActionPerformed

    private void fill_fees_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fill_fees_4KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_fill_fees_4KeyTyped

    private void remain_txt_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remain_txt_4KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_remain_txt_4KeyTyped

    private void fill_fees_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fill_fees_1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_fill_fees_1KeyTyped

    private void remain_txt_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remain_txt_1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_remain_txt_1KeyTyped

    private void fill_fees_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fill_fees_2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_fill_fees_2KeyTyped

    private void remain_txt_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remain_txt_2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_remain_txt_2KeyTyped

    private void fill_fees_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fill_fees_3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_fill_fees_3KeyTyped

    private void remain_txt_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remain_txt_3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_remain_txt_3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Class_fees_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Class_fees_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Class_fees_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Class_fees_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Class_fees_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JTextArea Class_3_area;
    private javax.swing.JButton Receipt_btn_1;
    private javax.swing.JButton Receipt_btn_2;
    private javax.swing.JButton Receipt_btn_3;
    private javax.swing.JButton Receipt_btn_4;
    private javax.swing.JButton Search_btn;
    private javax.swing.JTable class_3_table;
    private com.toedter.calendar.JDateChooser date_txt_1;
    private com.toedter.calendar.JDateChooser date_txt_2;
    private com.toedter.calendar.JDateChooser date_txt_3;
    private com.toedter.calendar.JDateChooser date_txt_4;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField fill_fees_1;
    private javax.swing.JTextField fill_fees_2;
    private javax.swing.JTextField fill_fees_3;
    private javax.swing.JTextField fill_fees_4;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton new_btn;
    private javax.swing.JButton print_btn1;
    private javax.swing.JTextField remain_txt_1;
    private javax.swing.JTextField remain_txt_2;
    private javax.swing.JTextField remain_txt_3;
    private javax.swing.JTextField remain_txt_4;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_middle_name;
    private javax.swing.JTextField txt_student_id;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
