
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class OTP_Generate extends javax.swing.JFrame {

    /**
     * Creates new form OTP_Generate
     */
    String checkotp="";
   
    public OTP_Generate() {
        initComponents();
        otp_number_txt.setText("7218502858");
        //otp_number_txt.setText("satav9096103138");9922620088guru
        this.setResizable(false);
        sv_btn.setEnabled(false);
        setIcon();
    }
    public void setIcon()
    {
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sc_logo.png")));
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gc.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sv_btn = new javax.swing.JButton();
        yes_btn = new javax.swing.JButton();
        otp_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cacl_btn = new javax.swing.JButton();
        otp_number_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adm_txt = new javax.swing.JTextField();
        nxt_btn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send OTP");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 108, 158));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 108, 158));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Send OTP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel1.setText("New Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Send OTP to this");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        sv_btn.setBackground(new java.awt.Color(22, 101, 158));
        sv_btn.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        sv_btn.setForeground(new java.awt.Color(255, 255, 255));
        sv_btn.setText("Save");
        sv_btn.setToolTipText("Submit");
        sv_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sv_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sv_btnActionPerformed(evt);
            }
        });
        jPanel2.add(sv_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 80, 30));

        yes_btn.setBackground(new java.awt.Color(22, 101, 158));
        yes_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        yes_btn.setForeground(new java.awt.Color(255, 255, 255));
        yes_btn.setText("Yes");
        yes_btn.setToolTipText("Submit");
        yes_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_btnActionPerformed(evt);
            }
        });
        jPanel2.add(yes_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 30));

        otp_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        otp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otp_txtActionPerformed(evt);
            }
        });
        otp_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                otp_txtKeyTyped(evt);
            }
        });
        jPanel2.add(otp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Number");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, 30));

        cacl_btn.setBackground(new java.awt.Color(22, 101, 158));
        cacl_btn.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        cacl_btn.setForeground(new java.awt.Color(255, 255, 255));
        cacl_btn.setText("Cancel");
        cacl_btn.setToolTipText("Submit");
        cacl_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cacl_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacl_btnActionPerformed(evt);
            }
        });
        jPanel2.add(cacl_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, 30));

        otp_number_txt.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jPanel2.add(otp_number_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel5.setText("Admin");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, 30));

        adm_txt.setEditable(false);
        adm_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(adm_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 170, 30));

        nxt_btn.setBackground(new java.awt.Color(22, 101, 158));
        nxt_btn.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        nxt_btn.setForeground(new java.awt.Color(255, 255, 255));
        nxt_btn.setText("Next");
        nxt_btn.setToolTipText("Submit");
        nxt_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nxt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(nxt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 80, 30));

        jPasswordField1.setEditable(false);
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel6.setText("Enter OTP");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 460, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sv_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sv_btnActionPerformed
        // TODO add your handling code here:
         Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;  
     conn=JavaConnect.ConnectDB();
     String a=adm_txt.getText();
     String b=jPasswordField1.getText();
     try
     {
          String sql="update Log_in set Password='"+b+"' where Admin='"+a+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
                 JOptionPane.showMessageDialog(null,"Password UPDATED Successfully");
                adm_txt.setText("");
                jPasswordField1.setText("");
         
     }
     catch(HeadlessException | SQLException ex)
     {
         JOptionPane.showMessageDialog(null, "Sorry Error Occured\n"+ex);
     }
    }//GEN-LAST:event_sv_btnActionPerformed

    private void yes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_btnActionPerformed
        // TODO add your handling code here:
       Random random = new Random();
		
        int x = random.nextInt(9999) + 100;
        // Print random doubles
        //System.out.println("Random Number is\t: "+x);
		String a=Integer.toString(x);
		//System.out.println("\nthe value of a is\t"+a);
		
		//System.out.println("\nthe value of b is\t"+b);
		checkotp=a; 
		try {
			// Construct data
			String apiKey = "apikey=" + "3GOVz3IiClk-mvKVagPUKvEBSzp0eCfRKI6qjL8ECZ";//GURU
			String message = "&message=" +"Your Conformatin OTP is "+a+" GURUKUL COACHING CLASSES";
			String sender = "&sender=" +"GURUKL";
			String numbers = "&numbers=" +otp_number_txt.getText();
                        //int unicode=1;
                        String unicode = "&unicode=" +"true";
			
			// Send data
			HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
			String data = apiKey + numbers + message + sender + unicode;
			conn.setDoOutput(true);
			conn.setRequestMethod("POST");
			conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
			conn.getOutputStream().write(data.getBytes("UTF-8"));
			final BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
			final StringBuffer stringBuffer = new StringBuffer();
			String line;
                       
			while ((line = rd.readLine()) != null) {
                            
                            JOptionPane.showMessageDialog(null, "Message\n"+line);
                            
				stringBuffer.append(line);
                                //System.out.println("the value of line is\t"+line);
                                if(line.startsWith("{\"errors\""))
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Sorry Error Occured");
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Alert\n"+"Message Send Successfully");
                                }
                                    
			}
			rd.close();
			
			//return stringBuffer.toString();
		} catch (HeadlessException | IOException e) {
			/*System.out.println("Error SMS "+e);
			return "Error "+e;*/
                        JOptionPane.showMessageDialog(null,e+ "\n\nMessage Send Not Successfully");
		}
    }//GEN-LAST:event_yes_btnActionPerformed

    private void cacl_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacl_btnActionPerformed
        // TODO add your handling code here:
                dispose();
    }//GEN-LAST:event_cacl_btnActionPerformed

    private void otp_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otp_txtKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_otp_txtKeyTyped

    private void nxt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxt_btnActionPerformed
        // TODO add your handling code here:
        String temp=otp_txt.getText();
         if(otp_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Sorry...Please Enter Valid OTP number");
        }
         else if(checkotp == null ? temp == null : checkotp.equals(temp))
        {
            adm_txt.setEditable(true);
            jPasswordField1.setEditable(true);
            sv_btn.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry OTP Not Match");
        }
    }//GEN-LAST:event_nxt_btnActionPerformed

    private void otp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otp_txtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_otp_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTP_Generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTP_Generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTP_Generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTP_Generate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTP_Generate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adm_txt;
    private javax.swing.JButton cacl_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton nxt_btn;
    private javax.swing.JLabel otp_number_txt;
    private javax.swing.JTextField otp_txt;
    private javax.swing.JButton sv_btn;
    private javax.swing.JButton yes_btn;
    // End of variables declaration//GEN-END:variables
}
